# Generated by Django 4.2.7 on 2023-12-11 22:57

import assets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('sn', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('description', models.TextField(verbose_name='描述')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('warranty_period', models.IntegerField(verbose_name='质保期')),
                ('user', models.CharField(max_length=100, verbose_name='领用人')),
                ('status', models.CharField(choices=[('normal', '正常'), ('scrap', '报废'), ('repair', '维修'), ('depreciation', '折旧'), ('other', '其他')], default='normal', max_length=100, verbose_name='资产状态')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=assets.models.department_path, verbose_name='二维码')),
                ('repair_count', models.IntegerField(default=0, verbose_name='维修次数')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
            },
        ),
        migrations.CreateModel(
            name='AssetManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=50, verbose_name='工号')),
            ],
            options={
                'verbose_name': '资产管理员',
                'verbose_name_plural': '资产管理员',
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='基地名称')),
            ],
            options={
                'verbose_name': '基地',
                'verbose_name_plural': '基地',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('asset_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='assets.assetmanager', verbose_name='资产管理员')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.base', verbose_name='基地')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='SparePartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='备件类型名称')),
            ],
            options={
                'verbose_name': '备件类型',
                'verbose_name_plural': '备件类型',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('contact_person', models.CharField(max_length=100, verbose_name='对接人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='对接电话')),
                ('address', models.TextField(verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='型号名称')),
                ('sn', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('warranty_period', models.IntegerField(verbose_name='配件质保期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.supplier', verbose_name='供应商')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.spareparttype', verbose_name='备件类型')),
            ],
            options={
                'verbose_name': '备件',
                'verbose_name_plural': '备件',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='维修日期')),
                ('applicant', models.CharField(max_length=100, verbose_name='申请维修人')),
                ('description', models.TextField(verbose_name='维修描述')),
                ('maintenance_type', models.CharField(choices=[('return', '返回供应商维修'), ('general', '信息部维修'), ('warranty', '供应商保修'), ('other', '其他维修')], default='return', max_length=100, verbose_name='维修类别')),
                ('repair_status', models.CharField(choices=[('repairing', '维修中'), ('arrived', '已送至供应商'), ('repaired', '已维修'), ('norepaire', '不维修'), ('discarded', '已废弃')], default='repairing', max_length=100, verbose_name='维修状态')),
                ('repair_start_time', models.DateTimeField(blank=True, null=True, verbose_name='维修开始时间')),
                ('repair_duration', models.DurationField(blank=True, null=True, verbose_name='维修持续时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='对应资产')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.department', verbose_name='维修部门')),
                ('spare_parts', models.ManyToManyField(blank=True, null=True, to='assets.sparepart', verbose_name='维修配件')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.supplier', verbose_name='维修供应商')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
            },
        ),
        migrations.AddField(
            model_name='assetmanager',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.base', verbose_name='基地'),
        ),
        migrations.AddField(
            model_name='assetmanager',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='assetmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department', verbose_name='使用部门'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.supplier', verbose_name='供应商'),
        ),
    ]
