# Generated by Django 4.2.7 on 2023-12-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='spare_parts',
            field=models.ManyToManyField(blank=True, to='assets.sparepart', verbose_name='维修配件'),
        ),
    ]
