# Generated by Django 4.2.7 on 2023-12-11 22:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='对接人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='对接电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name': '采购供应商',
                'verbose_name_plural': '采购供应商',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_part', models.CharField(max_length=255, verbose_name='设备型号')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit', models.CharField(max_length=50, verbose_name='单位')),
                ('applicant', models.CharField(max_length=100, verbose_name='申请人')),
                ('applicant_phone', models.CharField(max_length=20, verbose_name='申请人电话')),
                ('application_date', models.DateField(default=datetime.date.today, verbose_name='申请日期')),
                ('cost_number', models.CharField(max_length=100, verbose_name='费用单号')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='总价')),
                ('created_by', models.CharField(max_length=100, verbose_name='创建人')),
                ('delivery_status', models.CharField(choices=[('undelivered', '未发货'), ('delivered', '已发货'), ('arrived', '已到货'), ('returned', '已退货'), ('other', '其他')], default='undelivered', max_length=20, verbose_name='发货状态')),
                ('account_status', models.CharField(choices=[('unclaimed', '未报账'), ('submitted', '已提单'), ('claimed', '已报账'), ('discarded', '废弃单据'), ('other', '其他')], default='unclaimed', max_length=20, verbose_name='报账状态')),
                ('account_completed_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='报账完成时间')),
                ('invoice_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='发票号')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('base_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.base', verbose_name='基地名称')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department', verbose_name='费用部门')),
                ('spare_part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.spareparttype', verbose_name='设备名称')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_purchase_list.supplier', verbose_name='采购供应商')),
            ],
            options={
                'verbose_name': 'IT采购列表',
                'verbose_name_plural': 'IT采购列表',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='设备品牌')),
                ('type', models.CharField(choices=[('switch', '交换机'), ('router', '路由器'), ('network_card', '网卡'), ('firewall', '防火墙'), ('woc', 'WOC'), ('ac', 'AC行为管理'), ('ap', '无线控制器')], default='switch', max_length=50, verbose_name='类型')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('ip_address', models.GenericIPAddressField(verbose_name='设备IP')),
                ('purpose', models.TextField(verbose_name='用途')),
                ('serial_number', models.CharField(max_length=100, verbose_name='设备序列号')),
                ('web_link', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='购买日期')),
                ('warranty_period', models.IntegerField(verbose_name='质保期（天）')),
                ('out_of_warranty_date', models.DateField(blank=True, null=True, verbose_name='过保日期')),
                ('location', models.CharField(max_length=100, verbose_name='所在机房')),
                ('rack_position', models.CharField(max_length=100, verbose_name='机架位置')),
                ('maintenance_status', models.CharField(choices=[('under_maintenance', '维保中'), ('out_of_maintenance', '已过保')], max_length=50, verbose_name='维保状态')),
                ('service_object', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务对象')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='采购价格')),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='资产净值')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='账号')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='密码')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_purchase_list.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '网络设备',
                'verbose_name_plural': '网络设备',
            },
        ),
    ]
