# Generated by Django 4.2.7 on 2023-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='运单号'),
        ),
    ]
